### ISSUE TITLE
Does the latest build use the updated dictionary?

### ISSUE THREAD

**Issue by NestoriSyynimaa** [waf/WCF-Binary-Message-Inspector#3]
Hi,
and thanks for merging the new dictionary additions to master branch. 

I downloaded the new binary for Fiddler, but it still acts like it would be using the old dictionary.

I'm getting this:
```
<a:SequenceAcknowledgement xmlns:a="http://www.w3.org/2005/08/addressing">
	<a:ReplyTo>http://www.w3.org/2005/08/addressing/anonymous</a:ReplyTo>
</a:SequenceAcknowledgement>
```
While it should be this:
```
<a:ReplyTo>
	<a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
</a:ReplyTo>
```

**Comment by waf** [comment]
Ugh, you're right, thanks for raising this. I just downloaded the binary and confirmed it. This should be fixed in 894afc0c5d49b7e8bf9df6e545e5fe245fe59146 (latest master). Can you please check this on your side? Thanks.

**Comment by NestoriSyynimaa** [comment]
Still looks same:
```
<a:SequenceAcknowledgement xmlns:a="http://www.w3.org/2005/08/addressing"> 
   <a:ReplyTo>http://www.w3.org/2005/08/addressing/anonymous</a:ReplyTo>
</a:SequenceAcknowledgement>
```

**Comment by waf** [comment]
Hm, I've verified by decompiling the binary that it does in fact have the "DigestValue" changes:

![image](https://user-images.githubusercontent.com/97195/45756542-5043f480-bc4b-11e8-8731-6554600908b6.png)

One thing that changed in the release is now the DLL is `BinaryMessageFiddlerExtension.dll`. Is it possible you have multiple versions installed in your "Inspectors" directory?

**Comment by waf** [comment]
If you want to decompile it on your side, you can open the "Developer Command Prompt for VS 2017" (installed as part of visual studio) and run ildasm.exe on the DLL.

**Comment by NestoriSyynimaa** [comment]
Just one extension dll in the inspectors directory. 

I checked the dll with hex editor and it shows that the DigestValue is missing:
`T r a n s f o r m  D i g e s t M e t h o d  A d d r e s s `

I'll try the decompiler too and let you know.

**Comment by waf** [comment]
Just to confirm,  you're using the `BinaryMessageFiddlerExtension.dll` file, and not the older Fiddler2 version, right?

**Comment by NestoriSyynimaa** [comment]
Triple-checked everything and it is okay now. I tried to download the new one while Fiddler was running so I still had the first one you compiled after the fix. So thank you, this really saved my day!

**Comment by waf** [comment]
Got it, thanks for both adding the feature and pointing this out!
